### ISSUE TITLE
商品一覧の各商品を押した際にモーダルウィンドウを表示する

### ISSUE THREAD

**Issue by hiroki1238** [hiroki1238/nekonote-laravel-react-ts#68]
**現状**

- 商品を押しても商品詳細ページが存在しないため、買い出しの依頼ができない
- 商品一覧画面に余計な情報を載せすぎている

**理想**
- 商品を押すとモーダルウィンドウが表示される
- モーダルウィンドウ内に商品画像、商品の説明、依頼ボタンなどが表示される
- モーダルウィンドウ内で依頼を完結させる or 表示されているボタンを押すと別に用意されている依頼ページに飛ぶ はどちらでも良い

**Comment by Yota310** [comment]
内容は未完成。
